webserver-sunmedia:
  image: webdevops/php-nginx-dev:7.1
  volumes:
    - ./:/var/www
  links:
    - database-sunmedia
  environment:
    - WEB_DOCUMENT_ROOT=/var/www/public
    - WEB_DOCUMENT_INDEX=index.php
  ports:
    - "5080:80"

database-sunmedia:
  image: mysql:5.7
  volumes:
      - /var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=sunmedia
    - MYSQL_USER=sunmedia
    - MYSQL_PASSWORD=sunmedia
  ports:
    - "3306:3306"