easy_admin:
  design:
    menu:
      - { label: 'Dashboard', route: 'admin_dashboard', default: true }
      - label: 'General'
        children:
          - { entity: 'User', icon: 'asterisk' }
      - label: 'Create Ad'
        children:
          - { label: 'Component List', entity: 'Component', icon: 'asterisk' }
          - { label: 'Ad List', entity: 'MyAd', icon: 'asterisk' }