easy_admin:
  entities:
    User:
      class: App\Entity\User
      #disabled_actions: ["edit", "delete", "new"]
      disabled_actions: [ "delete"]
      list:
        actions: ["show"]
        fields:
          - id
          - username
          - email
      form:
        fields:
          - username
          - email
          - enabled
          - lastLogin
          - { property: 'plainPassword', type: 'text', type_options: { required: false } }
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN', 'ROLE_TC': 'ROLE_TC' } } }